version: '3.8'
services:
  localstack: 
    image: localstack-with-sam-cli
    container_name: localstack
    restart: on-failure
    environment: 
      - DEFAULT_REGION=ap-northeast-2
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=sa-east-1
    ports: 
      - '4566-4583:4566-4583'
    volumes:
      - "/Users/federicofailla/Downloads:/data/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"