version: '3.8'
services:
  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: mysql1
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vcdb
      MYSQL_USER: vcdb
      MYSQL_PASSWORD: vcdb
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
